// ── Error Response ──────────────────────────────────────

export interface ErrorResponse {
  success: false
  error: {
    code: string
    message: string
    messageTH?: string
    details?: unknown
    traceId?: string
  }
  timestamp: string
}

// ── Error Codes ─────────────────────────────────────────

export const UniLinkErrorCode = {
  // Authentication & Authorization
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_REFRESH_INVALID: 'AUTH_REFRESH_INVALID',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  AUTH_NODE_CERT_INVALID: 'AUTH_NODE_CERT_INVALID',
  AUTH_NODE_SUSPENDED: 'AUTH_NODE_SUSPENDED',

  // Verifiable Credential
  VC_NOT_FOUND: 'VC_NOT_FOUND',
  VC_REVOKED: 'VC_REVOKED',
  VC_EXPIRED: 'VC_EXPIRED',
  VC_SIGNATURE_INVALID: 'VC_SIGNATURE_INVALID',
  VC_ISSUER_UNKNOWN: 'VC_ISSUER_UNKNOWN',
  VC_ISSUER_SUSPENDED: 'VC_ISSUER_SUSPENDED',
  VC_CONTEXT_INVALID: 'VC_CONTEXT_INVALID',
  VC_TYPE_UNSUPPORTED: 'VC_TYPE_UNSUPPORTED',
  VC_ALREADY_REVOKED: 'VC_ALREADY_REVOKED',
  VC_STUDENT_MISMATCH: 'VC_STUDENT_MISMATCH',
  VC_ISSUE_FAILED: 'VC_ISSUE_FAILED',

  // Verifiable Presentation
  VP_SIGNATURE_INVALID: 'VP_SIGNATURE_INVALID',
  VP_CHALLENGE_MISMATCH: 'VP_CHALLENGE_MISMATCH',
  VP_CHALLENGE_EXPIRED: 'VP_CHALLENGE_EXPIRED',
  VP_DOMAIN_MISMATCH: 'VP_DOMAIN_MISMATCH',
  VP_HOLDER_MISMATCH: 'VP_HOLDER_MISMATCH',
  VP_EMPTY: 'VP_EMPTY',
  VP_VC_INVALID: 'VP_VC_INVALID',

  // Consent
  CONSENT_NOT_FOUND: 'CONSENT_NOT_FOUND',
  CONSENT_REQUIRED: 'CONSENT_REQUIRED',
  CONSENT_PENDING: 'CONSENT_PENDING',
  CONSENT_DENIED: 'CONSENT_DENIED',
  CONSENT_REVOKED: 'CONSENT_REVOKED',
  CONSENT_EXPIRED: 'CONSENT_EXPIRED',
  CONSENT_TOKEN_INVALID: 'CONSENT_TOKEN_INVALID',
  CONSENT_SCOPE_EXCEEDED: 'CONSENT_SCOPE_EXCEEDED',
  CONSENT_ALREADY_RESPONDED: 'CONSENT_ALREADY_RESPONDED',

  // Aggregate
  AGGREGATE_NODE_MISMATCH: 'AGGREGATE_NODE_MISMATCH',
  AGGREGATE_PROCESSING_FAILED: 'AGGREGATE_PROCESSING_FAILED',

  // Course Index
  COURSE_INDEX_NOT_FOUND: 'COURSE_INDEX_NOT_FOUND',
  EQUIVALENCY_NOT_FOUND: 'EQUIVALENCY_NOT_FOUND',

  // Course
  COURSE_NOT_FOUND: 'COURSE_NOT_FOUND',
  COURSE_INACTIVE: 'COURSE_INACTIVE',
  COURSE_INTEGRITY_FAILED: 'COURSE_INTEGRITY_FAILED',
  COURSE_NO_OUTCOMES: 'COURSE_NO_OUTCOMES',

  // Node
  NODE_NOT_FOUND: 'NODE_NOT_FOUND',
  NODE_ALREADY_EXISTS: 'NODE_ALREADY_EXISTS',
  NODE_SUSPENDED: 'NODE_SUSPENDED',
  NODE_UNREACHABLE: 'NODE_UNREACHABLE',

  // Transfer
  TRANSFER_NOT_FOUND: 'TRANSFER_NOT_FOUND',
  TRANSFER_ALREADY_EXISTS: 'TRANSFER_ALREADY_EXISTS',
  TRANSFER_GRADE_TOO_LOW: 'TRANSFER_GRADE_TOO_LOW',
  TRANSFER_LO_MISMATCH: 'TRANSFER_LO_MISMATCH',
  TRANSFER_ALREADY_PROCESSED: 'TRANSFER_ALREADY_PROCESSED',

  // Student
  STUDENT_NOT_FOUND: 'STUDENT_NOT_FOUND',
  STUDENT_ALREADY_EXISTS: 'STUDENT_ALREADY_EXISTS',
  STUDENT_DID_MISMATCH: 'STUDENT_DID_MISMATCH',
  STUDENT_INACTIVE: 'STUDENT_INACTIVE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',

  // Validation
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  INVALID_UUID: 'INVALID_UUID',
  INVALID_DID_FORMAT: 'INVALID_DID_FORMAT',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',

  // SIS
  SIS_WEBHOOK_INVALID: 'SIS_WEBHOOK_INVALID',
  SIS_SIGNATURE_INVALID: 'SIS_SIGNATURE_INVALID',
  SIS_DATA_INCOMPLETE: 'SIS_DATA_INCOMPLETE',

  // External
  EXTERNAL_PLATFORM_UNSUPPORTED: 'EXTERNAL_PLATFORM_UNSUPPORTED',
  EXTERNAL_VC_UNVERIFIABLE: 'EXTERNAL_VC_UNVERIFIABLE',
  EXTERNAL_PLATFORM_NOT_APPROVED: 'EXTERNAL_PLATFORM_NOT_APPROVED',
  EXTERNAL_SCORE_BELOW_MINIMUM: 'EXTERNAL_SCORE_BELOW_MINIMUM',
  EXTERNAL_VC_VERIFICATION_FAILED: 'EXTERNAL_VC_VERIFICATION_FAILED',
  EXTERNAL_CREDIT_LIMIT_EXCEEDED: 'EXTERNAL_CREDIT_LIMIT_EXCEEDED',
  EXTERNAL_ALREADY_PROCESSED: 'EXTERNAL_ALREADY_PROCESSED',
  EXTERNAL_NOT_FOUND: 'EXTERNAL_NOT_FOUND',

  // System
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  DATABASE_ERROR: 'DATABASE_ERROR',
  VAULT_ERROR: 'VAULT_ERROR',
  REDIS_ERROR: 'REDIS_ERROR',
  FCM_ERROR: 'FCM_ERROR',
} as const

export type UniLinkErrorCodeType = (typeof UniLinkErrorCode)[keyof typeof UniLinkErrorCode]

// ── UniLinkException ────────────────────────────────────

export class UniLinkException extends Error {
  constructor(
    public readonly code: UniLinkErrorCodeType,
    public readonly statusCode: number,
    message: string,
    public readonly messageTH?: string,
    public readonly details?: unknown,
  ) {
    super(message)
    this.name = 'UniLinkException'
  }
}
